# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

  # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
  providers:
    api_key_user_provider:
      id: AppBundle\Security\ApiKeyUserProvider

  firewalls:
    # disables authentication for assets and the profiler, adapt it according to your needs
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    api:
      pattern: ^/api/
      stateless: true
      simple_preauth:
        authenticator: AppBundle\Security\ApiKeyAuthenticator
      provider: api_key_user_provider

    main:
      anonymous: ~
